// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbipMQKIB8uWdcgsBTK9CLLXX1n6ud9gM',
    appId: '1:464218696811:web:85ad32ca3d2a800f82d52e',
    messagingSenderId: '464218696811',
    projectId: 'fluttergym-48b76',
    authDomain: 'fluttergym-48b76.firebaseapp.com',
    storageBucket: 'fluttergym-48b76.firebasestorage.app',
    measurementId: 'G-JFVPCT675K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeHh9Gzt77iFL1ipQ6RYuAdJKr3ODkfxk',
    appId: '1:464218696811:android:7f504d340a0dd90882d52e',
    messagingSenderId: '464218696811',
    projectId: 'fluttergym-48b76',
    storageBucket: 'fluttergym-48b76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA373AbtULIPTuDF1sembZqm2RFK85U9Bw',
    appId: '1:464218696811:ios:b7317e09f347395882d52e',
    messagingSenderId: '464218696811',
    projectId: 'fluttergym-48b76',
    storageBucket: 'fluttergym-48b76.firebasestorage.app',
    iosBundleId: 'com.example.fightersGymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA373AbtULIPTuDF1sembZqm2RFK85U9Bw',
    appId: '1:464218696811:ios:b7317e09f347395882d52e',
    messagingSenderId: '464218696811',
    projectId: 'fluttergym-48b76',
    storageBucket: 'fluttergym-48b76.firebasestorage.app',
    iosBundleId: 'com.example.fightersGymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbipMQKIB8uWdcgsBTK9CLLXX1n6ud9gM',
    appId: '1:464218696811:web:ae648691feac9ab882d52e',
    messagingSenderId: '464218696811',
    projectId: 'fluttergym-48b76',
    authDomain: 'fluttergym-48b76.firebaseapp.com',
    storageBucket: 'fluttergym-48b76.firebasestorage.app',
    measurementId: 'G-VV2D62XMGT',
  );
}
